# Generated by Django 4.2.16 on 2024-11-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_wishlist_created_at_alter_wishlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='language',
            field=models.CharField(choices=[('ko-KR', 'Korean'), ('en-US', 'English')], default='en-US', max_length=10),
        ),
    ]
